CC=gcc
all:
	$(CC) examples/project-2/alloc/policiesSet1.c impl/usm/usm.c impl/usm/hashmap.c impl/usm/list_sort.c impl/com/com.c impl/com/event.c impl/policies/alloc/alloc.c examples/project-2/project-2.c -o project-2 -lpthread -DDEBUG
